// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yzlxweofkhfrdvwqoomo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl6bHh3ZW9ma2hmcmR2d3Fvb21vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg4MjU5MjcsImV4cCI6MjA3NDQwMTkyN30.UYcP9_ei47xqx5yMefTRbb0y4k6rMR17ZYS8xI1FzLc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});